"""PDF export — generates an Architecture Brief from canvas state."""
from __future__ import annotations
from fpdf import FPDF

from core.capabilities import CAPABILITY_REGISTRY, LAYER_REGISTRY, get_layers_ordered, get_caps_for_layer
from core.constraints import CONSTRAINT_REGISTRY
from core.recommender import get_status, STATUS_RECOMMENDED, STATUS_MANUALLY_ADDED
from core.diagram import LAYER_COLORS, PATTERN_FLOWS, _get_active_by_layer


def _hex_to_rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


NAVY = (15, 23, 42)       # #0F172A
SLATE = (30, 41, 59)      # #1E293B
TEXT_LIGHT = (226, 232, 240)  # #E2E8F0
TEXT_MUTED = (148, 163, 184)  # #94A3B8
TEAL = (15, 118, 110)     # #0F766E
WHITE = (255, 255, 255)


class _BriefPDF(FPDF):
    """Custom PDF with dark theme footer."""

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*TEXT_MUTED)
        self.cell(0, 10, f"Generated by Enterprise AI Canvas  |  visakhsankar.com  |  Page {self.page_no()}", align="C")


def generate_pdf(
    pattern: str,
    scores: dict[str, int],
    manually_added: set,
    manually_removed: set,
    analysis: dict,
    active_constraints: set,
) -> bytes:
    """Generate a polished PDF architecture brief. Returns PDF bytes."""

    pdf = _BriefPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(20, 15, 20)

    active_by_layer = _get_active_by_layer(scores, manually_added, manually_removed)
    total_caps = sum(len(v) for v in active_by_layer.values())
    total_layers = len(active_by_layer)

    # ── Page 1: Cover + Analysis ─────────────────────────────────────────────

    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 12, "Enterprise AI Architecture Brief", ln=True)

    # Pattern subtitle
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*TEAL)
    pdf.cell(0, 10, pattern, ln=True)

    # Divider
    pdf.set_draw_color(*TEAL)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y() + 2, 190, pdf.get_y() + 2)
    pdf.ln(8)

    # Metrics row
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*NAVY)
    pdf.cell(55, 7, f"{total_caps} Capabilities", border=0)
    pdf.cell(55, 7, f"{total_layers} Layers", border=0)
    pdf.cell(55, 7, f"{len(active_constraints)} Constraints", border=0, ln=True)
    pdf.ln(6)

    # Analysis section
    _section_header(pdf, "PROBLEM ANALYSIS")

    fields = [
        ("Industry", analysis.get("industry", "N/A")),
        ("Use Case", analysis.get("use_case_summary", "N/A")),
        ("Scale", analysis.get("scale", "N/A")),
        ("Primary Concern", analysis.get("primary_concern", "N/A")),
    ]
    for label, value in fields:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*NAVY)
        pdf.cell(35, 6, f"{label}:")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(71, 85, 105)  # slate-600
        pdf.multi_cell(0, 6, value)

    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*NAVY)
    pdf.cell(35, 6, "Reasoning:")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.multi_cell(0, 5, analysis.get("reasoning", "N/A"))

    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*NAVY)
    pdf.cell(35, 6, "Signals:")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(71, 85, 105)
    signals_text = ", ".join(s.replace("_", " ") for s in analysis.get("signals", []))
    pdf.multi_cell(0, 5, signals_text or "None detected")

    # ── Constraints ──────────────────────────────────────────────────────────

    pdf.ln(6)
    _section_header(pdf, "ACTIVE CONSTRAINTS")

    if active_constraints:
        # Table header
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(*SLATE)
        pdf.set_text_color(*WHITE)
        pdf.cell(80, 7, "  Constraint", border=0, fill=True)
        pdf.cell(25, 7, "Type", border=0, fill=True, align="C")
        pdf.cell(40, 7, "Category", border=0, fill=True, align="C")
        pdf.ln()

        pdf.set_font("Helvetica", "", 8)
        for cid in sorted(active_constraints):
            c = CONSTRAINT_REGISTRY.get(cid)
            if not c:
                continue
            pdf.set_text_color(*NAVY)
            pdf.cell(80, 6, f"  {c['label']}", border=0)
            # Type badge
            is_hard = c["type"] == "hard"
            pdf.set_text_color(220, 38, 38) if is_hard else pdf.set_text_color(217, 119, 6)
            pdf.cell(25, 6, c["type"].upper(), border=0, align="C")
            pdf.set_text_color(71, 85, 105)
            pdf.cell(40, 6, c["category"], border=0, align="C")
            pdf.ln()
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*TEXT_MUTED)
        pdf.cell(0, 7, "No constraints active", ln=True)

    # ── Data Flow ────────────────────────────────────────────────────────────

    pdf.ln(6)
    _section_header(pdf, f"DATA FLOW — {pattern.upper()}")

    flows = PATTERN_FLOWS.get(pattern, PATTERN_FLOWS["Direct Prompting"])
    active_ids = set(active_by_layer.keys())
    step = 0
    pdf.set_font("Helvetica", "", 9)
    for src, dst, label in flows:
        if src in active_ids and dst in active_ids:
            step += 1
            src_name = LAYER_REGISTRY.get(src, {}).get("name", src)
            dst_name = LAYER_REGISTRY.get(dst, {}).get("name", dst)
            pdf.set_text_color(*TEAL)
            pdf.cell(8, 6, f"{step}.")
            pdf.set_text_color(*NAVY)
            pdf.cell(0, 6, f"{src_name}  ->  {dst_name}  ({label})", ln=True)

    # ── Capabilities by Layer ────────────────────────────────────────────────

    pdf.ln(6)
    _section_header(pdf, "RECOMMENDED STACK")

    for layer_id in get_layers_ordered():
        if layer_id not in active_by_layer:
            continue
        layer = LAYER_REGISTRY[layer_id]
        colors = LAYER_COLORS[layer_id]
        caps = active_by_layer[layer_id]

        # Check if we need a new page (leave room for header + at least 1 cap)
        if pdf.get_y() > 250:
            pdf.add_page()

        # Layer header bar
        r, g, b = _hex_to_rgb(colors["bg"])
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(*WHITE)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 8, f"  {layer['icon']}  {layer['name']}  ({len(caps)} selected)", ln=True, fill=True)
        pdf.ln(2)

        # Capabilities
        for c in caps:
            if pdf.get_y() > 270:
                pdf.add_page()

            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*NAVY)
            pdf.cell(0, 5, f"  {c['name']}", ln=True)

            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(71, 85, 105)
            pdf.cell(8, 5, "")
            pdf.cell(0, 5, f"{c['vendor']}  |  Cost: {c['trade_offs']['cost']}  |  Quality: {c['trade_offs']['quality']}  |  Latency: {c['trade_offs']['latency']}", ln=True)

            # Description (truncated)
            desc = c["description"][:200]
            pdf.set_font("Helvetica", "", 7.5)
            pdf.set_text_color(*TEXT_MUTED)
            pdf.cell(8, 4, "")
            pdf.multi_cell(0, 4, desc)
            pdf.ln(2)

        pdf.ln(3)

    # ── Simplified Visual Diagram ────────────────────────────────────────────

    pdf.add_page()
    _section_header(pdf, "ARCHITECTURE OVERVIEW")
    pdf.ln(4)

    # Draw layer boxes vertically
    box_w = 140
    box_h = 14
    gap = 6
    start_x = (210 - box_w) / 2  # center on A4
    y = pdf.get_y()

    layer_positions = {}  # layer_id -> (center_x, bottom_y)
    for layer_id in get_layers_ordered():
        if layer_id not in active_by_layer:
            continue
        layer = LAYER_REGISTRY[layer_id]
        colors = LAYER_COLORS[layer_id]
        caps = active_by_layer[layer_id]

        r, g, b = _hex_to_rgb(colors["bg"])
        pdf.set_fill_color(r, g, b)
        pdf.set_draw_color(r, g, b)
        pdf.rect(start_x, y, box_w, box_h, style="F")

        # Layer name
        pdf.set_xy(start_x, y + 1)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*WHITE)
        cap_text = ", ".join(c["name"] for c in caps[:3])
        if len(caps) > 3:
            cap_text += f" +{len(caps) - 3}"
        pdf.cell(box_w, 5, f"{layer['icon']}  {layer['name']}", align="C")
        pdf.set_xy(start_x, y + 6)
        pdf.set_font("Helvetica", "", 6.5)
        pdf.set_text_color(220, 220, 220)
        pdf.cell(box_w, 5, cap_text, align="C")

        layer_positions[layer_id] = (start_x + box_w / 2, y, y + box_h)
        y += box_h + gap

    # Draw flow arrows between layer boxes
    pdf.set_draw_color(*TEXT_MUTED)
    pdf.set_line_width(0.3)
    for src, dst, label in flows:
        if src in layer_positions and dst in layer_positions:
            sx, s_top, s_bot = layer_positions[src]
            dx, d_top, d_bot = layer_positions[dst]
            # Arrow from bottom of source to top of dest (or vice versa)
            if s_bot < d_top:
                pdf.line(sx, s_bot, dx, d_top)
            else:
                pdf.line(sx - 2, s_top, dx - 2, d_bot)

    return pdf.output()


def _section_header(pdf: _BriefPDF, title: str):
    """Render a section header with teal left border."""
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*TEAL)
    # Left border accent
    y = pdf.get_y()
    pdf.set_draw_color(*TEAL)
    pdf.set_line_width(1)
    pdf.line(20, y, 20, y + 6)
    pdf.cell(4, 6, "")
    pdf.cell(0, 6, title, ln=True)
    pdf.ln(3)
